image: Visual Studio 2015

environment:
  SHFBROOT:  C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
  SandCastleZipFile: SHFBInstaller.zip
  SandCastleUri: https://github.com/EWSoftware/SHFB/releases/download/v2017.1.28.0/SHFBInstaller_v20171.28.0.zip
  
install:
  - choco install gitversion.portable -pre -y
  - choco install nant -pre -y
  - ps: Start-FileDownload $env:SandCastleUri -FileName $env:SandCastleZipFile
  - cmd: 7z x SHFBInstaller.zip -y
  - ps: msiexec /i InstallResources\SandcastleHelpFileBuilder.msi /quiet /qn /norestart /log install.log


before_build:
  - nuget restore dotNetRDF.sln
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

configuration: Release

build:
  project: dotNetRDF.sln
  verbosity: minimal
  
test:
  categories:
    only:
      - Nothing

after_build:
  cmd: |
    "%ProgramFiles(x86)%\nant-0.92\bin\nant" -buildfile:Build\nant\dotnetrdf.build -D:dotnetrdf.version=%GitVersion_NuGetVersion% -D:dotnetrdf.nuspecversion=%GitVersion_NuGetVersion% -D:dotnetrdf.buildversion=%GitVersion_AssemblySemVer% no-compile dist-libs-stable dist-libs-nuget
  
artifacts:
  - path: 'Build\nuget\**\*.nupkg'
    name: NuGet Packages
  - path: 'dotNetRDF_library_*.zip'
    name: binaries

deploy:
  - provider: GitHub
    description: 'dotNetRDF $(GitVersion_SemVer)'
    auth_token:
      secure: j3GoyDavErTD91EcSTfNBbQyTc7tqpp+klmmz85xC4fjbE8Gl2brFjr8t3/Zzwmk
    on:
      appveyor_repo_tag: true 
    artifact: Build\shfb\Help.zip, Build\shfb\Help\dotNetRDFApi.chm, /.*\.nupkg/
  - provider: NuGet
    api_key:
      secure: URqGK+AnkTfy7Q36+5K2kNv2qpaI4ZOzjnRGry8tMiOMCtuqrwJWW/jSaEGhchuo
    on:
      appveyor_repo_tag: true 
    artifact: /((?!Spin).)*.nupkg/
